const actionTypes = {
	//page
	SYST_LANG_SET: "SYST_LANG_SET",
	DEVICE_DATA_LOADED: "DEVICE_DATA_LOADED",
	PAGE_CHANGED: "PAGE_CHANGED",

	//count
	INC_COUNT: "INCREMENT_COUNT",
	DEC_COUNT: "DECREMENT_COUNT",
	//sign in/up pages
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_ERROR: "SIGNIN_ERROR",
	SIGNIN_SUCCESS: "SIGNUP_SUCCESS",
	SIGNIN_ERROR: "SIGNUP_ERROR",
	SIGNUP_DATA_CHANGED:"SINGUP_DATA_CHANGED",
	USER_DATA_CHANGED: "USER_DATA_CHANGED"
};

export default actionTypes;
